name: Example workflow using Snyk fix
on: pull_request
jobs:
    init:
      runs-on: ubuntu-latest
      outputs:
        skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
        skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Scan Iac with kics
        - name: run kics Scan
          uses: checkmarx/kics-action@v1.3
          with:
            # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
            path: 'terraform,cfn-templates,my-other-sub-folder/Dockerfile'
            output_path: 'results.json'
        # Display the results in json format
        - name: display kics results
          run: |
            cat results.json
