name: KICS Scan
on:  
    workflow_dispatch:
jobs:
    init:
      runs-on: ubuntu-latest
      outputs:
        skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
        skip-not: ${{ steps.ci-skip-step.outputs.ci-skip-not }}
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Scan Iac with kics
        - name: run kics Scan
          uses: Checkmarx/kics-github-action@v1.4
          with:
            # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
            path: 'test-cases/terraform/'
            ignore_on_exit: results
            output_path: 'results.json'
        # Display the results in json format
        - name: display kics results
          run: |
            cat results.json
